filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/auth.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1
 
setup.kibana:

output.logstash:
  hosts: ["localhost:40001"]

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
